const envs = import.meta.env;

const Envs = {
  FIREBASE_API_KEY: envs.VITE_API_KEY,
  FIREBASE_AUTH_DOMAIN: envs.VITE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: envs.VITE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: envs.VITE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: envs.VITE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: envs.VITE_APP_ID,
};

export default Envs;
